# short class ID (human readable)
class = "PHIL 401"
# MySQL database user
db_user = "phil401"
# MySQL database password
db_password = "sleruyo62sti=a"
# list email addresses whose API keys get admin access
admins = ["julia_netter@brown.edu"]
# list email addresses who should receive notification emails
staff = ["julia_netter@brown.edu"]
# custom template directory
template_dir = "config/templates"
# custom resource directory (e.g., for images, CSS, JS)
resource_dir = "config/resources"
# a secret that will be hashed into user's API keys to make them unforgeable
secret = "172students"
# whether to send emails (set to false for development)
send_emails = true
# whether to reset the db (set to false for production)
prime = true
